# Análise Exploratória de Dados / Exploratory Data Analysis (EDA)

Uma boa EDA (Exploratory Data Analysis) pode ser pensada como uma sequência de perguntas que você faz ao dataset antes de partir para conclusões, visualizações mais sofisticadas ou Machine Learning.

- Um analista de dados é como um detetive: observa as pistas, encontra padrões e desvenda o que está por trás dos números.
- Dados são pistas. Padrões são evidências. E você é quem vai solucionar o mistério.
- Você não precisa de uma lupa para ser investigador — basta saber fazer as perguntas certas aos dados.


**Nos tempos dos reis, o conselheiro trazia informações para ajudar o governante a decidir. Hoje, o analista faz isso com dados. O rei tinha seus conselheiros. Hoje, empresas e organizações têm analistas de dados: pessoas que transformam informações em decisões.**

**Um analista de dados é como o conselheiro de um rei: transforma informações em conhecimento para orientar decisões importantes.**

# 0. Vamos começar. Primeiro importe pandas e os dados.

In [7]:
import pandas as pd

In [8]:
# Leia seu arquivo csv aqui

df = pd.read_csv("Tabela_Clubes.csv")

#### O próximo passo é dividir o processo em etapas

## 1. Entendimento geral do dataset

Antes de analisar os dados, descubra o que você recebeu.

### Qual é a unidade de observação? Uma pessoa? Uma venda? Um crime? Um dia?

In [9]:
df.head()

,Unnamed: 0,Ano,Pos.,Clubes,Vitorias,Derrotas,Empates,GolsF/S,Saldo,Qtd_Jogadores,Idade_Media,Estrangeiros,Valor_total,Media_Valor
0,0,2017,18,America-MG,10,10,18,30:47,-17,51,"24,8",0,27350000,536000
1,1,2017,7,Athletico-PR,16,9,13,54:37,17,52,24,3,37650000,724000
2,2,2017,6,Atletico-MG,17,8,13,56:43,13,50,"23,4",6,61350000,1230000
3,3,2017,11,Bahia,12,12,14,39:41,-2,48,"23,2",2,34900000,727000
4,4,2017,9,Botafogo,13,12,13,38:46,-8,45,"23,1",4,25550000,568000

A unidade de observacao e o resultado final de um clube em um campeonato de futebol

### Qual é a origem dos dados?

campeonatos Brasileiros de futebol - "Brasileirão"

### Quantas linhas e colunas existem?

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     200 non-null    int64
 1   Ano            200 non-null    int64
 2   Pos.           200 non-null    int64
 3   Clubes         200 non-null    str
 4   Vitorias       200 non-null    int64
 5   Derrotas       200 non-null    int64
 6   Empates        200 non-null    int64
 7   GolsF/S        200 non-null    str
 8   Saldo          200 non-null    int64
 9   Qtd_Jogadores  200 non-null    int64
 10  Idade_Media    200 non-null    str
 11  Estrangeiros   200 non-null    int64
 12  Valor_total    200 non-null    int64
 13  Media_Valor    200 non-null    int64
dtypes: int64(11), str(3)
memory usage: 25.4 KB

### O que cada coluna representa?

In [ ]:
for i in df.columns:
    print(f'- {i}:')

- Unnamed: 0:
- Ano:
- Pos.:
- Clubes:
- Vitorias:
- Derrotas:
- Empates:
- GolsF/S:
- Saldo:
- Qtd_Jogadores:
- Idade_Media:
- Estrangeiros:
- Valor_total:
- Media_Valor:

**descrição das colunas** 

- Unnamed: 0: Coluna redundante, é o indíces das linhas
- Ano: Anos que ocorreram os campeonatos
- Pos .: Posicao do clube no campeonato daquele ano
- Clubes: Nomes dos times de futebol
- Vitorias: Quantidade de vitórias do time naquele campeonato
- Derrotas: Quantidade de derrotas do time naquele campeonato
- Empates: Quantidade de empates do time naquele campeonato
- GolsF/S: Relação entre gols feitos / sofridos pelo time
- Saldo: Saldo de gols do time. Feitos - Sofridos.
- Qtd_Jogadores: Quantidade de jogadores totais do clube naquele ano
- Idade_Media: Idade media dos jogadores do time naquele ano
- Estrangeiros: Quantidade de jogadores estrangeiros no time naquele ano
- Valor_total: A soma do valor de todos os jogadores do time naquele ano
- Media_Valor: A media do valor de todos os jogadores do time naquele ano

### Qual é o período coberto pelos dados?

In [17]:
print(f'De {df['Ano'].min()} ate {df['Ano' ].max()}')

De 2008 ate 2017

### Existem identificadores únicos?

Não existe uma coluna com ID

### Existem colunas que parecem redundantes?

**COLUNAS REDUNDANTES**

- A coluna Unnamed 0 é desnecessária pois apenas representa os índices da linha.
- A coluna Saldo é redundante pois podemos acessar esses valores através de outra coluna GoslF/S

# 2. Tipos e estrutura das variáveis(colunas)

Para cada coluna:
- Ela é numérica, categórica, texto, data/hora ou booleana?
- O tipo armazenado corresponde ao tipo real da informação? Exemplo: Existem números armazenados como texto?
- Existem datas armazenadas como strings? 
- Existem categorias com grafias diferentes?
```text
    Exemplo:
    - "São Paulo"
    - "Sao Paulo"
    - "são paulo"
    Podem representar a mesma categoria.
```

In [ ]:
# A coluna Idade_Media estava com uma virgula ao inves de ponto, e por conta disso o tipo era String ao inves de float
df['Idade_Media']= df['Idade_Media'].apply(lambda x: float(x.replace(',','.')))

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     200 non-null    int64
 1   Ano            200 non-null    int64
 2   Pos.           200 non-null    int64
 3   Clubes         200 non-null    str
 4   Vitorias       200 non-null    int64
 5   Derrotas       200 non-null    int64
 6   Empates        200 non-null    int64
 7   GolsF/S        200 non-null    str
 8   Saldo          200 non-null    int64
 9   Qtd_Jogadores  200 non-null    int64
 10  Idade_Media    200 non-null    float64
 11  Estrangeiros   200 non-null    int64
 12  Valor_total    200 non-null    int64
 13  Media_Valor    200 non-null    int64
dtypes: float64(1), int64(11), str(2)
memory usage: 24.6 KB

# 3. Dados ausentes

Uma das perguntas mais importantes:

- Onde estão os dados faltantes e por que estão faltando?

### Existem valores NaN? Quantos por coluna?

dica: df.isna().sum()

In [22]:
df.isna().sum()

Unnamed: 0       0
Ano              0
Pos.             0
Clubes           0
Vitorias         0
Derrotas         0
Empates          0
GolsF/S          0
Saldo            0
Qtd_Jogadores    0
Idade_Media      0
Estrangeiros     0
Valor_total      0
Media_Valor      0
dtype: int64

### Qual percentual representa? Existem linhas completamente vazias?

dica: (df.isna().mean() * 100).sort_values(ascending=False)

# 4. Duplicidades

Pergunte:

- Existem linhas duplicadas?
- Existem registros duplicados pelo identificador que deveria ser único?
- O que define uma observação como única?
- Duplicatas são erros ou representam eventos legítimos?

dica: df.duplicated().sum()

In [26]:
df.duplicated().sum()

np.int64(0)

# 5.Qualidade e consistência dos dados

Aqui é uma etapa extremamente importante.

Aqui você começa a procurar anomalias.

Perguntas:

- Existem valores impossíveis?
- Existem valores negativos onde não deveriam existir?
- Existem idades de 300 anos?
- Existem datas futuras?
- Existem categorias inesperadas?
- Existem valores 0 que deveriam ser NaN?
- Existem erros de digitação?
- Existem unidades diferentes misturadas?

Exemplo:
```text
idade
-----
21
35
42
-5
999

Ou:

salário
-------
0
3500
4200
-600
5000
3500000


```
**A pergunta não é simplesmente:**

"Esse valor é diferente?"

Mas:

"Esse valor faz sentido dentro do contexto do problema?"

# 6. Distribuição das variáveis numéricas

Para cada variável numérica:

- Qual é o mínimo?
- Qual é o máximo?
- Qual é a média?

In [25]:
import numpy as np
colunas_numericas = []
for i in df.columns:
    if df[i].dtype != 'str':

        colunas_numericas.append(i)

df[colunas_numericas].agg({min, max, np.mean})

,Unnamed: 0,Ano,Pos.,Vitorias,Derrotas,Empates,Saldo,Qtd_Jogadores,Idade_Media,Estrangeiros,Valor_total,Media_Valor
min,0.0,2008.0,1.0,4.000,3.00,4.000,-57.0,20.00,21.600,0.000,2350000.0,67000.0
max,199.0,2017.0,20.0,24.000,17.00,28.000,40.0,77.00,26.500,8.000,115800000.0,2520000.0
mean,99.5,2012.5,10.5,13.855,10.28,13.855,0.0,43.23,23.988,2.885,39252800.0,912440.0

# 7. Distribuição das variáveis categóricas

Para cada variável categórica:

- Quais categorias existem?
- Quantas observações existem em cada categoria?
- Qual é a categoria mais frequente?
- Existem categorias muito raras?
- Existe desbalanceamento?
- Existem categorias inesperadas?

Perguntas importantes:

Existe uma categoria responsável por 90% dos registros?

Existem categorias com apenas 1 ou 2 observações?

Isso pode ser extremamente importante posteriormente.

In [27]:
df['Ano' ].value_counts()

Ano
2017    20
2016    20
2015    20
2014    20
2013    20
2012    20
2011    20
2010    20
2009    20
2008    20
Name: count, dtype: int64

In [28]:
df.groupby('Clubes')['Ano'].count().sort_values(ascending=False)

Clubes
Corinthians      10
Atletico-MG      10
Flamengo         10
Fluminense       10
Gremio           10
Cruzeiro         10
Santos           10
Sao Paulo        10
Palmeiras         9
Athletico-PR      9
Botafogo          9
Internacional     9
Coritiba          8
Sport             7
Vasco             7
Vitoria           7
Bahia             6
Chapecoense       5
Ponte Preta       5
Avai              5
Figueirense       5
Goias             5
Atletico-GO       4
America-MG        3
Nautico           3
Ceara             3
Criciuma          2
Prudente          2
Portuguesa        2
Guarani           1
Parana            1
Joinville         1
Santo Andre       1
Santa Cruz        1
Name: Ano, dtype: int64

# 8. Perguntas específicas do domínio

Essa é talvez a parte mais importante.

Você precisa perguntar:

O que é importante nesse problema específico?

Por exemplo:

**Dataset de vendas**

- Qual produto vende mais?
- Qual região vende mais?
- Quando as vendas aumentam?
- Qual produto possui maior faturamento?


**Dataset de crimes**

- Onde ocorrem mais ocorrências?
- Quando ocorrem?
- Quais naturezas predominam?
- Existem diferenças entre bairros?
- Existe concentração geográfica?

**Dataset de estudantes**

- Existe relação entre frequência e nota?
- Quais fatores estão associados à evasão?
- Como as notas variam entre turmas?
- Existe diferença por período?

**Dataset financeiro**

- Como o faturamento evolui?
- Quais produtos geram maior margem de lucro?
- Existem transações anormais?
- Existem valores extremos?

#### Quantos times unicos existem na tabela

In [32]:
df['Clubes'].nunique()

34

#### Quais os campeões de cada ano?

In [33]:
df[df['Pos.'] == 1].sort_values('Ano', ascending=True)

,Unnamed: 0,Ano,Pos.,Clubes,Vitorias,Derrotas,Empates,GolsF/S,Saldo,Qtd_Jogadores,Idade_Media,Estrangeiros,Valor_total,Media_Valor
187,187,2008,1,Flamengo,19,10,9,58:44,14,35,23.3,4,50400000,1440000
169,169,2009,1,Fluminense,20,11,7,62:36,26,50,23.5,4,42950000,859000
148,148,2010,1,Corinthians,21,8,9,53:36,17,51,23.6,4,69700000,1370000
129,129,2011,1,Fluminense,22,11,5,61:33,28,40,22.8,4,44200000,1110000
107,107,2012,1,Cruzeiro,23,7,8,77:37,40,44,24.4,1,15100000,343000
88,88,2013,1,Cruzeiro,24,8,6,67:38,29,32,25.7,4,41950000,1310000
64,64,2014,1,Corinthians,24,9,5,71:31,40,36,24.8,4,52850000,1470000
53,53,2015,1,Palmeiras,24,8,6,62:32,30,38,25.9,4,69950000,1840000
27,27,2016,1,Corinthians,21,9,8,50:30,20,41,23.4,3,49500000,1210000
13,13,2017,1,Palmeiras,23,11,4,64:26,38,48,24.8,4,88330000,1840000

#### Qual a idade média dos jogadores por ano

In [34]:
df.groupby('Ano')['Idade_Media'].mean()

Ano
2008    23.605
2009    23.905
2010    23.715
2011    23.830
2012    23.830
2013    24.645
2014    24.130
2015    24.470
2016    23.860
2017    23.890
Name: Idade_Media, dtype: float64

#### Qual é a média do valor total dos times por ano?

In [35]:
df.groupby('Ano')['Valor_total' ].mean()

Ano
2008    24098000.0
2009    36122500.0
2010    50362500.0
2011    44394000.0
2012    43923000.0
2013    27227500.0
2014    31293000.0
2015    40329500.0
2016    47124000.0
2017    47654000.0
Name: Valor_total, dtype: float64

#### Qual é o saldo de gols médio por time? (exiba o top 5)

In [36]:
df.groupby('Clubes')['Saldo'].sum().sort_values(ascending=False)

Clubes
Gremio           137
Corinthians      137
Cruzeiro          98
Santos            97
Sao Paulo         91
Internacional     74
Atletico-MG       73
Palmeiras         69
Flamengo          62
Fluminense        45
Botafogo          15
Athletico-PR      11
Portuguesa         2
Santo Andre      -15
Prudente         -18
Guarani          -20
Joinville        -22
Santa Cruz       -24
Coritiba         -30
Bahia            -30
Ceara            -32
Vasco            -35
Goias            -36
Chapecoense      -37
Parana           -39
Criciuma         -42
Ponte Preta      -43
Atletico-GO      -49
Vitoria          -60
America-MG       -70
Avai             -71
Sport            -75
Figueirense      -76
Nautico          -87
Name: Saldo, dtype: int64